### ISSUE TITLE
Port range for FreeSWITCH is wrong in diagram

### ISSUE THREAD

**Issue by dasJ** [bigbluebutton/bigbluebutton.github.io#169]
In images/22-connections.png, the external port range for FreeSWITCH ranges from 15634, however the real FreeSWITCH configuration begins its range at 16384.
I would fix that, but the sources of the diagram are not available.

Also, both the RAP scripts and bbb-web seem to connect to etherpad, those connections are missing as well.

**Comment by ffdixon** [comment]
Fixed the port range -- investigating whether the other components make a socket connection to etherpad
