### ISSUE TITLE
Storage example for Greenlight has an = too much at the end

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton.github.io#189]
https://docs.bigbluebutton.org/greenlight/gl-config.html#updating-from-version-prior-to-27

Example says:
```
    volumes:
      - ./log:/usr/src/app/log
      - ./storage:/usr/src/app/storage=
```

Working example should be:
```
    volumes:
      - ./log:/usr/src/app/log
      - ./storage:/usr/src/app/storage
```

Sorry for not sending a pull request, but currently travelling without equipment.

**Comment by farhatahmad** [comment]
Good catch and thank you for reporting it
