### ISSUE TITLE
document lockSettingsHideUserList in API

### ISSUE THREAD

**Issue by bilias** [bigbluebutton/bigbluebutton.github.io#211]
lockSettingsHideUserList option is not documented on https://docs.bigbluebutton.org/dev/api.html#create

**Comment by hex-m** [comment]
There are multiple new settings that are not yet in the documentation. e.g. `breakoutRoomsEnabled`.

I think the current list of available API calls would be [this](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java).

**Comment by ffdixon** [comment]
Thanks for pointing this out.  We'll update the docs.

**Comment by hex-m** [comment]
Comparing the [list](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-common-web/src/main/java/org/bigbluebutton/api/ApiParams.java) in the source with the [parameters-table](https://github.com/bigbluebutton/bigbluebutton.github.io/blob/master/_posts/2015-04-05-api.md#create) for the create call - this is the diff:

```
breakoutRoomsEnabled
breakoutRoomsPrivateChatEnabled
breakoutRoomsRecord
endWhenNoModerator
fullName
guestPolicy
html5InstanceId
lockSettingsHideUserList
lockSettingsLockOnJoinConfigurable
logoutTimer
meetingEndedURL
password
recordID
redirect
webVoice
```

**Comment by sualko** [comment]
@hex-m I think does parameters are not only related to the create endpoint. E.g. `password` and `fullName` are part of the join call.
