### ISSUE TITLE
404 link in "Upgrading from BigBlueButton 2.2"

### ISSUE THREAD

**Issue by caminsha** [bigbluebutton/bigbluebutton.github.io#215]
As I went through the docs I've found a dead link.

If you'll go [this](https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22) link you'll see the following text:
> If you installed a previous version of BigBlueButton 2.2 using the step-by-step instructions, then you should backup any custom changes first (or setup https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart to automatically apply your updates), and then upgrade using the commands below.

The link in this section gives me a 404 error.

As I dont' really know where this link should point to I didnt' fix it myself and it would be great if you'll fix this.

**Comment by ffdixon** [comment]
Thanks for pointing this out -- fixed the broken link.

**Comment by caminsha** [comment]
> Thanks for pointing this out -- fixed the broken link.

Thanks.
