### ISSUE TITLE
Turn server setup - needs opening tcp/80?

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton.github.io#266]
At https://docs.bigbluebutton.org/2.2/setup-turn-server.html#generating-tls-certificates , for generating certificate, the reader runs the following command:

$ sudo certbot certonly --standalone --preferred-challenges http -d <turn.example.com>

This need a open tcp/80 port. Would "sudo ufw open http" be necessary in case they set up firewall?

**Comment by basisbit** [comment]
The documentation is written, so that the firewall only gets configured / enabled after the user did execute the certbot.

In general, the documentation is written to be used by server administrators. Someone who doesn't know how to temporarily open and close a port for such a task should not get support for installing a BBB server (just my personal opinion)

**Comment by lonesomewalker** [comment]
As much as i agree with basisbit (i also hate misconfigured spam servers), i also think the documentation should be more open for "starters".

**Comment by hiroshisuga** [comment]
Believe or not, the documentation is already written so well that even an unskilled people can setup everything, and that's why you experts are kept busy with troubleshooting ;-)

> firewall only gets configured / enabled after the user did execute the certbot
Agreed, and that's how the problem (in fact it was mine) comes. Usually a user would go through all the steps including the initial certbot execution without problems, and then forgets that it needs tcp/80 and later configures ufw blocking tcp/80, then suddenly realises that the automatic certificate renewal is not working at all.

**Comment by basisbit** [comment]
@hiroshisuga tcp/80 should NOT be opened continuously, but instead should only be opened on demand for the certbot (and only if necessary), and then be closed again.
