### ISSUE TITLE
2.3 Missing Customization page

### ISSUE THREAD

**Issue by Tarekajaj** [bigbluebutton/bigbluebutton.github.io#275]
in 2.2 we had this page where it has all the customization options including options and custom parameters we can pass to html5 client when joining in a user
https://docs.bigbluebutton.org/2.2/customize.html

http://web.archive.org/web/20210128082700/https://docs.bigbluebutton.org/2.2/customize.html#passing-custom-parameters-to-the-client-on-join

This page is missing completely in the latest documentation version and link to version 2.2 is also missing,

**Comment by antobinary** [comment]
Customize was moved under Administration
https://docs.bigbluebutton.org/admin/customize.html

It is relevant for 2.3 and 2.4 too, so it made sense to relocate it under Administration. Please let us know if I forgot to change some link to the page...
