### ISSUE TITLE
the certificate for bigbluebutton.org has expired

### ISSUE THREAD

**Issue by mherrb** [bigbluebutton/bigbluebutton.github.io#288]
Firefox says, when connecting to https://bigbluebutton.org/ : 

Websites prove their identity via certificates, which are valid for a set time period. The certificate for bigbluebutton.org expired on 6/21/2021.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by mherrb** [comment]
Apparently  it has been renewed now.

**Comment by ffdixon** [comment]
Fixed -- thanks!
