### ISSUE TITLE
Possible error in sed command while installing greenlight following docs.

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton.github.io#388]
## What is happening.

In the section for [installing greenlight](https://docs.bigbluebutton.org/greenlight/gl-install.html#using-docker-compose) there is the following command:

``` bash
export pass=$(openssl rand -base64 24); sed -i 's/POSTGRES_PASSWORD=password/POSTGRES_PASSWORD='$pass'/g' docker-compose.yml;sed -i 's/DB_PASSWORD=password/DB_PASSWORD='$pass'/g' .env
```

The problem is that the `$(openssl rand -base64 24)` part of the command can generate a `/` character, which will enter in conflict with the slashes already from the `sed -i` command.

### My suggestion:

Replace that command for:

``` bash
export pass=$(openssl rand -base64 24); sed -i 's\POSTGRES_PASSWORD=password\POSTGRES_PASSWORD='$pass'\g' docker-compose.yml;sed -i 's\DB_PASSWORD=password\DB_PASSWORD='$pass'\g' .env
```
that way, I don't think that  a string can be generated with the counter-slash in it. But either way, we can also add a minor note warning the user that this error is likely to appear.

Edit: 

Some logs of the original error: 

![image](https://user-images.githubusercontent.com/69865537/167485013-ae19ab16-db1e-4eaf-a570-f147ce5384e1.png)

**Comment by farhatahmad** [comment]
Hi @GuiLeme - thats a good catch. We could change it to `openssl rand -hex` or try to pull out the `/` before passing it on. What do you think?

**Comment by GuiLeme** [comment]
> Hi @GuiLeme - thats a good catch. We could change it to `openssl rand -hex` or try to pull out the `/` before passing it on. What do you think?

So, about the `openssl` I think that it could do the trick, but we would have to install this `openssl` package in the docker, right?

About the other Idea: you mean pulling `/` out by removing it from the newly generated string, isn't it?

**Comment by farhatahmad** [comment]
Yes please - If you switch to `hex` you won't need the `\` solution since hex is only `a-f` and `0-9`
