### ISSUE TITLE
Typo in Markdown in Documentation

### ISSUE THREAD

**Issue by MBM1607** [bigbluebutton/bigbluebutton.github.io#393]
https://docs.bigbluebutton.org/2.5/dev.html#recommended-on-linux-host-we-highly-recommend-using-docker-dev

![Screenshot 2022-05-23 at 12-47-15 BigBlueButton Development](https://user-images.githubusercontent.com/47133639/169770463-aace7fa8-65eb-47ea-b95e-6b08173aee7b.png)

**Comment by ffdixon** [comment]
Thanks!  Fixed in https://github.com/bigbluebutton/bigbluebutton.github.io/commit/0bf78493ce1d7cb91a63562b82b15247b50988f0.
