### ISSUE TITLE
"Join" Documentation error?

### ISSUE THREAD

**Issue by rm-code** [bigbluebutton/bigbluebutton.github.io#394]
Shouldn't this section say "There is only an XML response for this call if the redirect parameter is set to `false`" (instead of `true`)?

![image](https://user-images.githubusercontent.com/11627131/172568907-4ed77d42-f706-4b2a-b851-01670c9cbb47.png)

**Comment by ffdixon** [comment]
Thanks -- we'll review.

**Comment by gustavotrott** [comment]
You are right @rm-code.
I just sent a fix for it! Thanks
