### ISSUE TITLE
Broken Links on Support Pages

### ISSUE THREAD

**Issue by MBM1607** [bigbluebutton/bigbluebutton.github.io#413]
Version 2.2 installation guide is linked from multiple pages but it is not longer available.

## Pages
https://docs.bigbluebutton.org/support/release-notes.html
https://docs.bigbluebutton.org/admin/configure-firewall.html
https://docs.bigbluebutton.org/admin/customize.html#apply-confsh
https://docs.bigbluebutton.org/support/getting-help.html
https://docs.bigbluebutton.org/support/road-map.html

**Comment by MBM1607** [comment]
I can take this up, but need clarification on what link to replace this with?

Should I use 2.5 link https://docs.bigbluebutton.org/2.5/install.html?

or should I use the generic https://docs.bigbluebutton.org/install/install.html?

**Comment by paulmenzel** [comment]
Please use the generic one.

**Comment by ffdixon** [comment]
The generic one
 
  https://docs.bigbluebutton.org/install/install.html

Will link you to the latest install docs (in this case 2.5).
