### ISSUE TITLE
Create a topic or a page to explain bigbluebutton.properties configuration

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton.github.io#81]
Currently we have no topic or page that explains bigbluebutton.properties configuration entries and their impact on meetings. All what we have are scattered discussions over the forums.

**Comment by matiasilva** [comment]
Since this was added two years ago, I'm not sure what the status was then however as it stands the current documentation in the form of comments is quite adequate. Consider closing this issue.
